<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InterestTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $interests = [
            'Fútbol',
            'Baloncesto',
            'Tenis',
            'Natación',
            'Ciclismo',
            'Running',
            'Yoga',
            'Gimnasia',
            'Surf',
            'Escalada',
            'Boxeo',
            'Artes marciales',
            'Senderismo',
            'Fitness',
            'Golf',
            'Pintura',
            'Música (tocar instrumentos)',
            'Teatro',
            'Danza',
            'Cine',
            'Fotografía',
            'Escultura',
            'Literatura',
            'Poesía',
            'Arte digital',
            'Historia del arte',
            'Museos y exposiciones',
            'Moda y diseño',
            'Manualidades',
            'Cómic y manga',
            'Programación',
            'Desarrollo de videojuegos',
            'Robótica',
            'Inteligencia Artificial',
            'Realidad virtual',
            'Criptomonedas',
            'Blockchain',
            'Gadgets y tecnología',
            'Innovación tecnológica',
            'Startups y emprendimiento',
            'Diseño web',
            'Aplicaciones móviles',
            'Ciberseguridad',
            'Big Data',
            'Internet de las cosas (IoT)',
            'Viajar',
            'Turismo cultural',
            'Turismo de aventura',
            'Camping',
            'Ecoturismo',
            'Gastronomía local',
            'Fotografía de viajes',
            'Road trips',
            'Exploración urbana',
            'Viajes en moto',
            'Viajes en bicicleta',
            'Viajes en tren',
            'Viajes low cost',
            'Viajes de lujo',
            'Viajes espirituales',
            'Cocina internacional',
            'Repostería',
            'Cocina vegana',
            'Cocina vegetariana',
            'Vinos y enología',
            'Cerveza artesanal',
            'Coctelería',
            'Alimentos orgánicos',
            'Ferias gastronómicas',
            'Recetas tradicionales',
            'Food blogging',
            'Dietas saludables',
            'Comida rápida',
            'Comida étnica',
            'Fermentación y conservas',
            'Idiomas',
            'Ciencia',
            'Matemáticas',
            'Filosofía',
            'Historia',
            'Psicología',
            'Economía',
            'Política',
            'Medio ambiente',
            'Astronomía',
            'Neurociencia',
            'Innovación educativa',
            'Investigación científica',
            'Tecnología educativa',
            'Aprendizaje autodidacta',
            'Videojuegos',
            'Series y películas',
            'Música (escuchar)',
            'Podcasts',
            'Streaming (Twitch, YouTube)',
            'Juegos de mesa',
            'Juegos de rol',
            'Cosplay',
            'Magia y ilusionismo',
            'Stand-up comedy',
            'Reality shows',
            'Anime',
            'K-pop',
            'Cine independiente',
            'Festivales de música',
            'Voluntariado comunitario',
            'Ayuda humanitaria',
            'Protección animal',
            'Medio ambiente y sostenibilidad',
            'Derechos humanos',
            'Igualdad de género',
            'Educación infantil',
            'Salud mental',
            'Cooperación internacional',
            'Activismo social',
            'Reciclaje y ecología',
            'Agricultura urbana',
            'Desarrollo comunitario',
            'Inclusión social',
            'Filantropía',
            'Meditación',
            'Mindfulness',
            'Desarrollo personal',
            'Productividad',
            'Minimalismo',
            'Finanzas personales',
            'Inversiones',
            'Bienestar emocional',
            'Autocuidado',
            'Moda sostenible',
            'Decoración de interiores',
            'Jardinería',
            'Mascotas',
            'Vida saludable',
            'Ahorro y frugalidad',
        ];

        // Insertar los intereses en la base de datos
        foreach ($interests as $interest) {
            DB::table('interests')->insert([
                'name' => $interest,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
