<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Skill;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            'Impresión 3D',
            '3ds Max',
            'Abrazos',
            'Diseño de accesibilidad',
            'Actuación',
            'Fotografía de deportes de acción',
            'Activismo',
            'Administración de comunidades',
            'Administración de cuentas',
            'Adobe After Effects',
            'Adobe Audition',
            'Experto certificado en Adobe',
            'Instructor certificado en Adobe',
            'Adobe Creative Cloud',
            'Adobe CS',
            'Adobe Dreamweaver',
            'Adobe Illustrator',
            'Adobe InDesign',
            'Adobe Lightroom',
            'Adobe Photoshop',
            'Adobe Premiere',
            'Adobe XD',
            'Aventuras',
            'Fotografía publicitaria',
            'Defensa de causas',
            'Metodología Agile',
            'Coaching Agile',
            'Agricultura',
            'AJAX',
            'Aliteración',
            'Orden alfabético',
            'Lenguaje de señas americano',
            'Análisis de datos',
            'Análisis de negocios',
            'Android',
            'Animación',
            'Ropa',
            'Diseño de aplicaciones',
            'Desarrollo de aplicaciones',
            'Tiro con arco',
            'Diseño arquitectónico',
            'Fotografía arquitectónica',
            'Archivado',
            'Arduino',
            'Arquitectura',
            'Arte digital',
            'Historia del arte',
            'Inteligencia artificial',
            'Gestión artística',
            'Ashtanga',
            'Hacer buenas preguntas',
            'ASP',
            'ASP.NET',
            'Lenguaje ensamblador',
            'Desarrollo de audiencias',
            'Audio',
            'Autor',
            'AutoCAD',
            'Cuidado de niños',
            'Desarrollo back-end',
            'Baile',
            'Repostería',
            'Coctelería',
            'Beber',
            'Ser ninja',
            'Ser increíble',
            'Danza del vientre',
            'Diseño de bebidas',
            'Bingo',
            'Bitcoin',
            'Blogging',
            'Diseño de libros',
            'Publicación de libros',
            'Caza con arco',
            'Lluvia de ideas',
            'Branding',
            'Estrategia de marca',
            'Romper cosas',
            'Ir a brunch',
            'Consultoría empresarial',
            'Diseño empresarial',
            'Desarrollo empresarial',
            'Inteligencia empresarial',
            'Creación de redes empresariales',
            'C',
            'C#',
            'C++',
            'CAD',
            'Caligrafía',
            'Gestión de campañas',
            'Cantar',
            'Cartas',
            'Coaching profesional',
            'Cartografía',
            'Caricaturismo',
            'Contratación de catering',
            'Acariciar gatos',
            'Cerámica',
            'Cerveza',
            'Promoción del cambio',
            'Diseño de personajes',
            'Coreografía',
            'Cine',
            'Cinematografía',
            'Relaciones con clientes',
            'ClojureScript',
            'Payaso',
            'Coaching',
            'Preparar cócteles',
            'Preparación de café',
            'Colaboración',
            'Color',
            'Comedia',
            'Comercio',
            'Comida',
            'Fotografía comercial',
            'Comunicación',
            'Diseño de comunicaciones',
            'Estrategia de comunicación',
            'Construcción de comunidades',
            'Gestión de comunidades',
            'Composición musical',
            'Hackeo de computadoras',
            'Desarrollo conceptual',
            'Conectar ideas',
            'Construcción',
            'Contabilidad',
            'Creación de contenido',
            'Desarrollo de contenido',
            'Gestión de contenido',
            'Marketing de contenido',
            'Estrategia de contenido',
            'Conversación',
            'Cocina',
            'Edición de textos',
            'Redacción publicitaria',
            'Identidad corporativa',
            'Diseño de vestuario',
            'Desarrollo de cursos',
            'Diseño de portadas',
            'Manualidades',
            'Marketing creativo',
            'Redacción creativa',
            'Creatividad',
            'Crochet',
            'Crucigramas',
            'CSS',
            'Cultura',
            'Curaduría',
            'Experiencia del cliente',
            'Soporte al cliente',
            'Bromas de papá',
            'Danza',
            'Analítica de datos',
            'Desarrollo de bases de datos',
            'Sistemas de datos',
            'Visualización de datos',
            'Estrategia de diseño',
            'Pensamiento de diseño',
            'Romper tecnología',
            'Dibujar',
            'Diseño digital',
            'Marketing digital',
            'Estrategia digital',
            'Dirección creativa',
            'Dirección de arte',
            'Director',
            'Diseño',
            'Diseño de alimentos',
            'Diseño de calzado',
            'Diseño de experiencia',
            'Diseño de interiores',
            'Diseño de joyas',
            'Diseño de juegos',
            'Diseño de muebles',
            'Diseño de productos',
            'Diseño de restaurantes',
            'Diseño de revistas',
            'Diseño de servicios',
            'Diseño de sonido',
            'Diseño gráfico',
            'Diseño industrial',
            'Diseño social',
            'Diseño sostenible',
            'Diseño tipográfico',
            'Diseño urbano',
            'Diseño web',
            'Dividir la cuenta',
            'Fotografía documental',
            'Hacer el bien',
            'Acariciar perros',
            'Donas',
            'Garabatear',
            'Dormir',
            'Soñar',
            'Drupal',
            'Comer',
            'Comer chocolate',
            'Comer cupcakes',
            'Comer donas',
            'Ecommerce',
            'Edición de fotos',
            'Edición de video',
            'Edición',
            'Editorial',
            'Diseño editorial',
            'Ilustración editorial',
            'Educación',
            'Efectos visuales',
            'Ingeniería eléctrica',
            'Diseño electrónico',
            'Etiqueta de correos electrónicos',
            'Email marketing',
            'Emoji',
            'Empatizar',
            'Compromiso de empleados',
            'Encuadernación',
            'Ingeniería',
            'Emprendimiento',
            'Entusiasmo',
            'Escalar cosas',
            'Estrategia',
            'Etnografía',
            'Eventos',
            'Fotografía de eventos',
            'Planificación de eventos',
            'Diseño de exposiciones',
            'Experiencia de usuario',
            'Dormir profundamente',
            'Pintar caras',
            'Facilitación',
            'Diseño floral',
            'Diseño sostenible',
        ];

        foreach ($skills as $skill) {
            Skill::create(['name' => $skill]);
        }
    }
}
